/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/5340bf74-652c-48e7-a7bc-577aa08d9113 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  int random_value;
  bool buttom;
  bool led_switch1;
  bool led_switch2;
  bool led_switch3;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

int LED1 = 13;
int LED2 = 14;
int LED3 = 26;

int parpadeoCount = 0;

void setup() {
  pinMode(LED1, OUTPUT);
  pinMode(LED2, OUTPUT);
  pinMode(LED3, OUTPUT);
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(4000); 
  random_value = 500;
  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  
  ArduinoCloud.update();
  // Your code here
  
  led_switch1 = true;
  if(buttom){
  Serial.println("el boton esta encendido");
  }
  onLedSwitch1Change();
  
  led_switch2 = true;
  onLedSwitch2Change();
  delay(500);
  led_switch2 = false;
  onLedSwitch2Change();
  
  led_switch3 = true;
  onLedSwitch3Change();
  delay(10000);
  led_switch3 = false;
  onLedSwitch3Change();
  
  led_switch2 = true;
  onLedSwitch2Change();
  delay(500);
  led_switch2 = false;
  onLedSwitch2Change();  
  
}
/*
  Since LedSwitch1 is READ_WRITE variable, onLedSwitch1Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onLedSwitch1Change()  {
  // Add your code here to act upon LedSwitch1 change
  randomSeed(millis());
  
  int startTime = millis();
  int initialTime = millis();
  
  while (startTime - initialTime < 10000) {
    // Enciende LED1
    digitalWrite(LED1, HIGH);
    if(buttom){
      Serial.println("SIRVEEE");
      break;
    }
    Serial.println(buttom);
    startTime = millis();
    ArduinoCloud.update();
  }
    
  for (int i = 0; i < 3; i++) {
    digitalWrite(LED1, HIGH);
    delay(500);
    digitalWrite(LED1, LOW);
    delay(500);
  }
}

/*
  Since LedSwitch2 is READ_WRITE variable, onLedSwitch2Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onLedSwitch2Change()  {
  // Add your code here to act upon LedSwitch2 change
  if (led_switch2) {
    digitalWrite(LED2, HIGH);
  } else {
    digitalWrite(LED2, LOW);
  }
}

/*
  Since LedSwitch3 is READ_WRITE variable, onLedSwitch3Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onLedSwitch3Change()  {
  // Add your code here to act upon LedSwitch3 change
  if (led_switch3) {
    digitalWrite(LED3, HIGH);
  } else {
    digitalWrite(LED3, LOW);
  }  
  
}


/*
  Since Buttom is READ_WRITE variable, onButtomChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onButtomChange()  {
  // Add your code here to act upon Buttom change
}
